edition = "2024"
hard_tabs = true
wrap_comments = true
comment_width = 140
max_width = 120
format_code_in_doc_comments = true
format_macro_matchers = true
format_strings = true
indent_style = "Block"
inline_attribute_width = 40
match_arm_blocks = false
match_block_trailing_comma = true
imports_granularity = "Module"
newline_style = "Unix"
normalize_doc_attributes = true
overflow_delimited_expr = true
reorder_impl_items = true
group_imports = "StdExternalCrate"
spaces_around_ranges = true
struct_field_align_threshold = 100
trailing_comma = "Vertical"
use_field_init_shorthand = true
use_small_heuristics = "Max"
use_try_shorthand = true
